#!/usr/bin/env node
// Writes src/version.ts with the values GetServerInfo reports but the running
// service cannot find out by itself: the release version and the SHA-256 of
// the contract text the service was built from. Run before tsc/esbuild/vitest.
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function releaseVersion() {
  const fromEnv = process.env.MASUDA_SANDBOX_VERSION?.trim();
  if (fromEnv) return fromEnv.replace(/^v/, "");
  try {
    const tag = execFileSync("git", ["describe", "--tags", "--exact-match", "--match", "v*", "HEAD"], { cwd: root, stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
    if (tag) return tag.replace(/^v/, "");
  } catch {
    // Not on a tagged commit, or not a git checkout at all (e.g. an unpacked tarball).
  }
  return "dev";
}

const proto = readFileSync(path.join(root, "proto/masuda/sandbox/v1/sandbox.proto"));
const version = releaseVersion();
const contractSha256 = createHash("sha256").update(proto).digest("hex");

const out = `// Generated by scripts/gen-version.mjs. Do not edit.
export const VERSION = ${JSON.stringify(version)};
export const CONTRACT_SHA256 = ${JSON.stringify(contractSha256)};
`;
writeFileSync(path.join(root, "src/version.ts"), out);
process.stdout.write(`src/version.ts: version=${version} contract_sha256=${contractSha256}\n`);
